name: CD

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  release:

jobs:
  doc:
    runs-on: ubuntu-latest
    name: Build and deploy doc
    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Build example site
        run: pnpm docs:build
        env:
          BASE_URL: /vuepress-plugin-docgen/

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist

  npm:
    runs-on: ubuntu-latest
    name: Publish to npm
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Restore build cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: |
            dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Publish npm package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
