name: CI

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build plugin
    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Build plugin
        run: pnpm build

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            dist
          key: ${{ runner.os }}-build-${{ github.sha }}

  release-please:
    runs-on: ubuntu-latest
    needs: build
    name: Process version
    steps:
      - uses: actions/checkout@v2

      - name: Process version
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: vuepress-plugin-docgen
